version: "3.9"

services:
  mongo:
    image: mongo:latest
    container_name: mongo-rs
    restart: unless-stopped
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis-server
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

  minio:
    image: minio/minio:latest
    container_name: minio-server
    restart: unless-stopped
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000" # API / S3 endpoint
      - "9001:9001" # MinIO Console
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    volumes:
      - minio_data:/data
    networks:
      - app-network

  mc-setup:
    image: quay.io/minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      mc alias set myminio http://storage:9000 admin password123;
      mc anonymous set download myminio/game-assets;
      mc anonymous set download myminio/file;
      exit 0;
      "

volumes:
  mongo_data:
  redis_data:
  minio_data:

networks:
  app-network:
    driver: bridge
